ID: 2020_11_16_CCLE_full
Title: "2020-11-16 CCLE Full"
HPC_ID: jeff.alvarez
Contact_name: "Jeff Alvarez"
Organism: "Human"
fastqs: /databricks/db-orpheus/data/samples
bam: /databricks/db-orpheus/data/human_sample.bam
ref:
        fa: /dbfs/references/Homo_sapiens_assembly19.fasta
        dict: /dbfs/references/Homo_sapiens_assembly19.dict
        gtf: /databricks/db-orpheus/data/Human_B37.3_chr1.gtf
        build: Human_B37.3
        known_sites: /dbfs/references/00-common_all.vcf.gz
