ID: 2020_08_18_test
Title: "2020-08-18 Docker Test"
HPC_ID: jeff.alvarez
Contact_name: "Jeff Alvarez"
Organism: "Human"
fastqs: /databricks/db-orpheus/data/samples
bam: /databricks/db-orpheus/data/human_sample.bam
ref:
        fa: /databricks/db-orpheus/ref/Human_B37.3_chr1.fasta
        gtf: /databricks/db-orpheus/ref/Human_B37.3_chr1.gtf
        build: Human_B37.3
known_sites: /databricks/db-orpheus/ref/dbsnp_138.b37.chr_1.vcf.gz
