ID: 2020_08_05_test
Title: "2020-08-05 Docker Test"
HPC_ID: jeff.alvarez
Contact_name: "Jeff Alvarez"
Organism: "Human"
fastqs: /databricks/orpheus/input/
bam: /databricks/orpheus/outs/star/untreated/Aligned.sortedByCoord.out.bam 
ref:
        fa: /databricks/orpheus/ref/Human_B37.3_chr1.fasta
        gtf: /databricks/orpheus/ref/Human_B37.3_chr1.gtf
        build: Human_B37.3
known_sites: /databricks/orpheus/ref/dbsnp_138.b37.chr_1.vcf.gz
