ID: 2020_08_17_test
Title: "2020-08-17 Docker Test"
HPC_ID: jeff.alvarez
Contact_name: "Jeff Alvarez"
Organism: "Human"
fastqs: /databricks/orpheus/data/samples
bam: /databricks/orpheus/data/human_sample.bam 
ref:
        fa: /databricks/orpheus/data/Human_B37.3_chr1.fasta
        gtf: /databricks/orpheus/data/Human_B37.3_chr1.gtf
        build: Human_B37.3
known_sites: /databricks/orpheus/data/dbsnp_138.b37.chr_1.vcf.gz
